[package]
name = "slated"
version = "0.1.0"
edition = "2021"

[dependencies]
slate-common = { path = "../slate-common" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
nix = { version = "0.29", features = ["signal", "process"] }
tracing = "0.1"
toml = "0.8"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
aisdk = { version = "0.5", features = ["anthropic", "openai", "google"] }
futures = "0.3"
glob = "0.3"
grep-regex = "0.1"
grep-searcher = "0.1"
ignore = "0.4"
schemars = "1"
