[package]
name = "codiv-common"
version.workspace = true
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
libc = "0.2"
rand = "0.8"
portable-pty = "0.9"
crossbeam-channel = "0.5"
chrono = { version = "0.4", features = ["serde"] }
url = { version = "2", features = ["serde"] }
oauth2 = "5.0.0"
open = "5.3.3"
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1"
tokio = { version = "1", features = ["rt", "macros"] }
toml_edit = "0.22"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
